modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/MerchantPug/apugli/issues"

[[mods]]
modId="apugli"
version="${version}"
displayName="Apugli"
#updateJSONURL=""
displayURL="https://github.com/MerchantPug/apugli"
logoFile="pack.png"
authors="MerchantPug, RaymondBlaze"
description="Pug's extension to A Power Library."

[[dependencies.apugli]]
    modId="forge"
    mandatory=true
    versionRange="[40.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apugli]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apugli]]
    modId="apoli"
    mandatory=true
    versionRange="[1.18.2-2.3.3.6,)"
    ordering="AFTER"
    side="BOTH"