name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  ORG_GRADLE_PROJECT_merchantpugUsername: ${{ secrets.MAVEN_NAME }}
  ORG_GRADLE_PROJECT_merchantpugPassword: ${{ secrets.MAVEN_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  ENVIRONMENT: publishing

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Upload releases
        run: ./gradlew downloadOriginsLibs build github publishCurseForge modrinth publish --stacktrace